#theme: jekyll-theme-minima
title: VMagicMirror
author: 獏星(ばくすたー)
description: Mirror-like software to reflect yourself as VRM avatar, without any special devices.
summary: VMagicMirrorはキーボードとマウスを使ってVRMアバターを鏡写しのように動かせるソフトウェアです。

latest_version: v1.6.0
latest_update: 2020/12/30

sass:
    style: compressed
