#theme: jekyll-theme-minima
title: VMagicMirror
author: 獏星(ばくすたー)
description: Mirror-like software to reflect yourself as VRM avatar, without any special devices.
summary: VMagicMirrorはキーボードとマウスを使ってVRMアバターを鏡写しのように動かせるソフトウェアです。

latest_version: v4.2.0
latest_update: 2025/08/24

sass:
    style: compressed

defaults:
  -
    values:
      lang: 'ja'

collections_dir: langs
collections:
  japanese:
    output: true
    permalink: /:path/
  english:
    output: true
    permalink: /en/:path/

plugins:
  - jekyll-sitemap
